# COVID-19 ICU Admission 

COVID-19 pandemic impacted the whole world, overwhelming healthcare systems - unprepared for such intense and lengthy request for ICU beds, professionals, personal protection equipment and healthcare resources.
Brazil recorded first COVID-19 case on February 26 and reached community transmission on March 20.

Based on the data available, is it feasible to predict which patients will need intensive care unit support?
The aim is to provide tertiary and quarternary hospitals with the most accurate answer, so ICU resources can be arranged or patient transfer can be scheduled.

# Dataset
This dataset contains anonymized data from Hospital Sírio-Libanês, São Paulo and Brasilia. All data were anonymized following the best international practices and recommendations. Data has been cleaned and scaled by column according to Min Max Scaler to fit between -1 and 1.

In [1]:
#importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
#importing the dataset
dataset = pd.read_excel('/content/drive/MyDrive/Kaggle_Sirio_Libanes_ICU_Prediction.xlsx')
dataset = pd.DataFrame(dataset)
dataset

AGE_ABOVE65 AGE_PERCENTIL  ...    WINDOW  ICU
0               1          60th  ...       0-2    0
1               1          60th  ...       2-4    0
2               1          60th  ...       4-6    0
3               1          60th  ...      6-12    0
4               1          60th  ...  ABOVE_12    1
...           ...           ...  ...       ...  ...
1920            0          50th  ...       0-2    0
1921            0          50th  ...       2-4    0
1922            0          50th  ...       4-6    0
1923            0          50th  ...      6-12    0
1924            0          50th  ...  ABOVE_12    0

[1925 rows x 230 columns]

In [3]:
#Removing the unnecessary columns
dataset.drop(["AGE_PERCENTIL"], axis = 1, inplace = True)
dataset = dataset[dataset.columns.drop(list(dataset.filter(regex='_MEAN')))]
dataset = dataset[dataset.columns.drop(list(dataset.filter(regex='_MIN')))]
dataset = dataset[dataset.columns.drop(list(dataset.filter(regex='_MAX')))]
dataset = dataset[dataset.columns.drop(list(dataset.filter(regex='_DIFF')))]
dataset

AGE_ABOVE65  GENDER  ...    WINDOW  ICU
0               1       0  ...       0-2    0
1               1       0  ...       2-4    0
2               1       0  ...       4-6    0
3               1       0  ...      6-12    0
4               1       0  ...  ABOVE_12    1
...           ...     ...  ...       ...  ...
1920            0       1  ...       0-2    0
1921            0       1  ...       2-4    0
1922            0       1  ...       4-6    0
1923            0       1  ...      6-12    0
1924            0       1  ...  ABOVE_12    0

[1925 rows x 55 columns]

In [4]:
#encoding the range like parameters with numerals
'''we have encoded:
0-2 as 1
2-4 as 2 
4-6 as 3
6-12 as 4
ABOVE_12 as 5'''
dataset["WINDOW"].replace({"0-2": "1", "2-4": "2","4-6": "3","6-12": "4","ABOVE_12": "5"}, inplace=True)
dataset["GENDER"].replace({1 : 1.0, 0 : 0.0},inplace = True)
dataset["AGE_ABOVE65"].replace({1 : 1.0, 0 : 0.0},inplace = True)
dataset

AGE_ABOVE65  GENDER  ...  WINDOW  ICU
0             1.0     0.0  ...       1    0
1             1.0     0.0  ...       2    0
2             1.0     0.0  ...       3    0
3             1.0     0.0  ...       4    0
4             1.0     0.0  ...       5    1
...           ...     ...  ...     ...  ...
1920          0.0     1.0  ...       1    0
1921          0.0     1.0  ...       2    0
1922          0.0     1.0  ...       3    0
1923          0.0     1.0  ...       4    0
1924          0.0     1.0  ...       5    0

[1925 rows x 55 columns]

In [5]:
#Splitting into dependant and independant variable sets
X = dataset.iloc[:,:-1]
Y = dataset.iloc[:,54]
X

AGE_ABOVE65  GENDER  ...  OXYGEN_SATURATION_MEDIAN  WINDOW
0             1.0     0.0  ...                  0.736842       1
1             1.0     0.0  ...                  0.578947       2
2             1.0     0.0  ...                       NaN       3
3             1.0     0.0  ...                  0.736842       4
4             1.0     0.0  ...                  0.631579       5
...           ...     ...  ...                       ...     ...
1920          0.0     1.0  ...                  0.789474       1
1921          0.0     1.0  ...                  0.578947       2
1922          0.0     1.0  ...                  0.736842       3
1923          0.0     1.0  ...                  0.473684       4
1924          0.0     1.0  ...                  0.631579       5

[1925 rows x 54 columns]

In [6]:
#Removing the infinite and null values
X = X.replace([np.inf, -np.inf],np.nan) #removing the infinite values
X = X.replace(np.nan,9) #replacing the null values with 9(any random number)
X

AGE_ABOVE65  GENDER  ...  OXYGEN_SATURATION_MEDIAN  WINDOW
0             1.0     0.0  ...                  0.736842       1
1             1.0     0.0  ...                  0.578947       2
2             1.0     0.0  ...                  9.000000       3
3             1.0     0.0  ...                  0.736842       4
4             1.0     0.0  ...                  0.631579       5
...           ...     ...  ...                       ...     ...
1920          0.0     1.0  ...                  0.789474       1
1921          0.0     1.0  ...                  0.578947       2
1922          0.0     1.0  ...                  0.736842       3
1923          0.0     1.0  ...                  0.473684       4
1924          0.0     1.0  ...                  0.631579       5

[1925 rows x 54 columns]

In [7]:
#Filling the missing values
X=np.asarray(X).astype(np.float32)
Y=np.asarray(Y).astype(np.float32) #converting to numpy array, as tensorflow doesnt accept lists
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=9, strategy='mean') #now treat 9 as missing values
imputer = imputer.fit(X[:,11:53])
X[:,11:53] = imputer.transform(X[:,11:53])
X

array([[ 1.        ,  0.        ,  0.        , ..., -0.2857143 ,
         0.7368421 ,  1.        ],
       [ 1.        ,  0.        ,  0.        , ...,  0.53571427,
         0.57894737,  2.        ],
       [ 1.        ,  0.        ,  0.        , ...,  0.06379831,
         0.74858755,  3.        ],
       ...,
       [ 0.        ,  1.        ,  0.        , ...,  0.14285715,
         0.7368421 ,  3.        ],
       [ 0.        ,  1.        ,  0.        , ...,  0.2857143 ,
         0.47368422,  4.        ],
       [ 0.        ,  1.        ,  0.        , ...,  0.07142857,
         0.6315789 ,  5.        ]], dtype=float32)

In [8]:
#Splitting the dataset into test and train set
from sklearn.model_selection import train_test_split
X_train,x_test,Y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [9]:
#Building the ANN
ann = tf.keras.models.Sequential() #buiding the ann by 3 layers
ann.add(tf.keras.layers.Dense(units= 18, activation='relu'))
ann.add(tf.keras.layers.Dense(units= 15, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1 , activation='sigmoid'))

In [10]:
#Applying Callbacks
from keras.callbacks import EarlyStopping
es = EarlyStopping(monitor ="val_loss",  mode ="min" , verbose=1 , patience=10) 
#to prevent the overfitting of the model
cp = tf.keras.callbacks.ModelCheckpoint('model-{epoch:03d}.model',monitor='val_loss',verbose=0,save_best_only=True,mode='auto')
#to save the best epoch model based on the val_loss...it is saved as .model file or as a folder in your working directory

In [11]:
#Training the ANN
ann.compile(optimizer='adam' , loss='binary_crossentropy' ,metrics= ['accuracy']) #training and compiling the ann
ann.fit(X_train,Y_train,batch_size=32,epochs=150,validation_data=(x_test,y_test),callbacks =[cp])

Epoch 1/150
49/49 [==============================] - 3s 10ms/step - loss: 0.6250 - accuracy: 0.6846 - val_loss: 0.5786 - val_accuracy: 0.7091
INFO:tensorflow:Assets written to: model-001.model/assets
Epoch 2/150
49/49 [==============================] - 0s 3ms/step - loss: 0.5325 - accuracy: 0.7358 - val_loss: 0.5370 - val_accuracy: 0.7506
INFO:tensorflow:Assets written to: model-002.model/assets
Epoch 3/150
49/49 [==============================] - 0s 3ms/step - loss: 0.4746 - accuracy: 0.7946 - val_loss: 0.5104 - val_accuracy: 0.7818
INFO:tensorflow:Assets written to: model-003.model/assets
Epoch 4/150
49/49 [==============================] - 0s 3ms/step - loss: 0.4445 - accuracy: 0.7967 - val_loss: 0.4964 - val_accuracy: 0.7792
INFO:tensorflow:Assets written to: model-004.model/assets
Epoch 5/150
49/49 [==============================] - 0s 3ms/step - loss: 0.4437 - accuracy: 0.8018 - val_loss: 0.4830 - val_accuracy: 0.7974
INFO:tensorflow:Assets written to: model-005.model/assets
Epoc

In [12]:
#Predicting the Test result
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5) #just to remove the probability
y_pred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [

In [13]:
#Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
ac = accuracy_score(y_test,y_pred)
print("Confusion Matrix :")
print(cm)
print("Accuracy Percentage :", ac*100 ,'%')

Confusion Matrix :
[[259  14]
 [ 48  64]]
Accuracy Percentage : 83.8961038961039 %
